version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/invoicemanagement.client"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "malek"
    assignees:
      - "malek"

  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    directory: "/InvoiceManagement.Server"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "malek"
    assignees:
      - "malek"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "malek"
    assignees:
      - "malek"

  # Disable Docker updates to avoid conflicts
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "monthly"
  #   open-pull-requests-limit: 3
  #   reviewers:
  #     - "malek"
  #   assignees:
  #     - "malek"
