name: Cleanup Dependabot Branches

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  cleanup:
    name: Cleanup Old Dependabot Branches
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete old Dependabot branches
      run: |
        echo "Cleaning up old Dependabot branches..."
        
        # Get all remote branches
        git fetch --all
        
        # List all branches
        branches=$(git branch -r | grep 'origin/dependabot' | sed 's/origin\///')
        
        if [ -z "$branches" ]; then
          echo "No Dependabot branches found"
          exit 0
        fi
        
        echo "Found Dependabot branches:"
        echo "$branches"
        
        # Delete each Dependabot branch
        for branch in $branches; do
          echo "Deleting branch: $branch"
          git push origin --delete "$branch" || echo "Failed to delete $branch"
        done
        
        echo "✅ Cleanup completed"
